### ISSUE TITLE
Gateway Timeout helm kanboard

### ISSUE THREAD

**Issue by tipsandtoolscoaching** [nicholaswilde/helm-charts#2]
Hi

When I use from outside cluster the url http://kanboard.192.168.1.203.nip.io/  in the web explorer show me the following error:

Gateway Timeout
Server error - server 192.168.1.203 is unreachable at this moment.

Please retry the request or contact your administrator.

I have kubernetes nginx with load balancer metallb and my cluster is onpremise with version 1.18.10

**Comment by nicholaswilde** [comment]
Make sure the IP address of your ingress controller matches the [nip.io](https://nip.io/) IP address.

**Comment by tipsandtoolscoaching** [comment]
Hi
Thanks!
