### ISSUE TITLE
[WikiJS] Running as wrong user

### ISSUE THREAD

**Issue by krangence** [nicholaswilde/helm-charts#22]
WikiJS is running as the wrong user, and currently runs as user _abc_ as shown the below printscreen:

https://i.imgur.com/0AKAbFh.png

This then results in the below error: 

https://i.imgur.com/oDVpfOF.png

**Comment by nicholaswilde** [comment]
I believe this may be a problem with the linuxserver.io image. Perhaps the issue needs to made over there? https://github.com/linuxserver/docker-wikijs/issues

**Comment by nicholaswilde** [comment]
Perhaps you just need to change the `PUID` and `GPID` values. https://docs.linuxserver.io/general/understanding-puid-and-pgid

**Comment by ChipWolf** [comment]
Surely the `PUID` and `GPID` should match whatever the `securityContext` is on the mount @nicholaswilde?

**Comment by nicholaswilde** [comment]
It looks like this might related to [this pr](https://github.com/linuxserver/docker-wikijs/pull/8).

**Comment by ChipWolf** [comment]
> 
> 
> It looks like this might related to [this pr](https://github.com/linuxserver/docker-wikijs/pull/8).

Turns out it's not, already verified, not applicable to k8s deployments. @krangence and I have tested this thoroughly.
It's due to the `securityContext.fsGroup` not set in accordance with the application user in the container.
