### ISSUE TITLE
[hedgedoc] oidc configuration

### ISSUE THREAD

**Issue by kfox1111** [nicholaswilde/helm-charts#26]
**Helm chart name:**

hedgedoc

**Describe the solution you'd like:**

That there are configuration options for setting up oidc authentication.

**Comment by nicholaswilde** [comment]
I will look into this. Thanks for the request!

**Comment by nicholaswilde** [comment]
I haven't tried this myself, but have you tried setting the [environmental variables](https://docs.hedgedoc.org/configuration/#oauth2-login)?
