### ISSUE TITLE
[hedgedoc] Ingress should not have annotations by default

### ISSUE THREAD

**Issue by stv0g** [nicholaswilde/helm-charts#8]
The ingress template adds the following annotation by default:

`nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24`

https://github.com/nicholaswilde/helm-charts/blob/main/charts/hedgedoc/values.yaml#L28

Can we remove this? I see no reason it should be there.

**Comment by nicholaswilde** [comment]
I'll look into it.

**Comment by nicholaswilde** [comment]
See [hedgedoc-0.1.12] (https://github.com/nicholaswilde/helm-charts/releases/tag/hedgedoc-0.1.12)
